config/routes.rb
FundMgmtApplication::Application.routes.draw do
  resources :fines

  resources :events

  resources :users

  resources :user_roles

  resources :cities

  resources :states

  resources :countries

end

app/models/fine.rb
class Fine < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/controllers/fines_controller.rb
class FinesController < ApplicationController
  # GET /fines
  # GET /fines.xml
  def index
    @fines = Fine.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @fines }
    end
  end

  # GET /fines/1
  # GET /fines/1.xml
  def show
    @fine = Fine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @fine }
    end
  end

  # GET /fines/new
  # GET /fines/new.xml
  def new
    @fine = Fine.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @fine }
    end
  end

  # GET /fines/1/edit
  def edit
    @fine = Fine.find(params[:id])
  end

  # POST /fines
  # POST /fines.xml
  def create
    @fine = Fine.new(params[:fine])

    respond_to do |format|
      if @fine.save
        format.html { redirect_to(@fine, :notice => 'Fine was successfully created.') }
        format.xml  { render :xml => @fine, :status => :created, :location => @fine }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @fine.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /fines/1
  # PUT /fines/1.xml
  def update
    @fine = Fine.find(params[:id])

    respond_to do |format|
      if @fine.update_attributes(params[:fine])
        format.html { redirect_to(@fine, :notice => 'Fine was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @fine.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /fines/1
  # DELETE /fines/1.xml
  def destroy
    @fine = Fine.find(params[:id])
    @fine.destroy

    respond_to do |format|
      format.html { redirect_to(fines_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/fines_helper.rb
module FinesHelper
end

app/views/fines/_form.html.erb
<%= form_for(@fine) do |f| %>
  <% if @fine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fine.errors.count, "error") %> prohibited this fine from being saved:</h2>

      <ul>
      <% @fine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fine_amount %><br />
    <%= f.text_field :fine_amount %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :event %><br />
    <%= f.text_field :event %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fines/edit.html.erb
<h1>Editing fine</h1>

<%= render 'form' %>

<%= link_to 'Show', @fine %> |
<%= link_to 'Back', fines_path %>

app/views/fines/index.html.erb
<h1>Listing fines</h1>

<table>
  <tr>
    <th>Fine amount</th>
    <th>Comment</th>
    <th>User</th>
    <th>Event</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fines.each do |fine| %>
  <tr>
    <td><%= fine.fine_amount %></td>
    <td><%= fine.comment %></td>
    <td><%= fine.user %></td>
    <td><%= fine.event %></td>
    <td><%= link_to 'Show', fine %></td>
    <td><%= link_to 'Edit', edit_fine_path(fine) %></td>
    <td><%= link_to 'Destroy', fine, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fine', new_fine_path %>

app/views/fines/new.html.erb
<h1>New fine</h1>

<%= render 'form' %>

<%= link_to 'Back', fines_path %>

app/views/fines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Fine amount:</b>
  <%= @fine.fine_amount %>
</p>

<p>
  <b>Comment:</b>
  <%= @fine.comment %>
</p>

<p>
  <b>User:</b>
  <%= @fine.user %>
</p>

<p>
  <b>Event:</b>
  <%= @fine.event %>
</p>


<%= link_to 'Edit', edit_fine_path(@fine) %> |
<%= link_to 'Back', fines_path %>